version: "3.8"

volumes:
  postgres_data: { }
  minio_data: { }

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

services:
  postgres:
    image: docker.io/bitnami/postgresql:14
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/bitnami/postgresql'
      - '../postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh'
    environment:
      - POSTGRESQL_USERNAME=oneflow
      - POSTGRESQL_DATABASE=oneflow
      - POSTGRESQL_PASSWORD=secret
    networks:
      default:
        ipv4_address: 172.29.1.10

  minio:
    image: bitnami/minio:latest
    environment:
      - MINIO_ROOT_USER=minio_access_key
      - MINIO_ROOT_PASSWORD=minio_secret_key
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - 'minio_data:/data'

    networks:
      default:
        ipv4_address: 172.29.1.11

  create_default_minio_bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set enminio http://minio:9000 minio_access_key minio_secret_key;
      /usr/bin/mc mb enminio/oneflow;
      /usr/bin/mc policy set public enminio/oneflow;
      exit 0;
      "
    networks:
      default:
        ipv4_address: 172.29.1.12